<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722142212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create favorites and add recipe favorite counters.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, recipe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_favorite_user ON favorite (user_id)');
        $this->addSql('CREATE INDEX idx_favorite_recipe ON favorite (recipe_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_favorite_user_recipe ON favorite (user_id, recipe_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED959D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recipe ADD favorite_count INT DEFAULT 0 NOT NULL');
        $this->addSql('CREATE INDEX idx_recipe_favorite_count ON recipe (favorite_count)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED959D8A214');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP INDEX idx_recipe_favorite_count');
        $this->addSql('ALTER TABLE recipe DROP favorite_count');
    }
}
