<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723145048 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create reports and add recipe moderation status.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, target_type VARCHAR(30) NOT NULL, target_id INT NOT NULL, reason VARCHAR(50) NOT NULL, message TEXT DEFAULT NULL, status VARCHAR(30) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reporter_id INT NOT NULL, reviewed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784FC6B21F1 ON report (reviewed_by_id)');
        $this->addSql('CREATE INDEX idx_report_status ON report (status)');
        $this->addSql('CREATE INDEX idx_report_target ON report (target_type, target_id)');
        $this->addSql('CREATE INDEX idx_report_reporter ON report (reporter_id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql("ALTER TABLE recipe ADD moderation_status VARCHAR(30) DEFAULT 'visible' NOT NULL");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784FC6B21F1');
        $this->addSql('DROP TABLE report');
        $this->addSql('ALTER TABLE recipe DROP moderation_status');
    }
}
